name: devstack
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  firebase_core: ^2.5.0
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1
  sqflite: ^2.2.4+1
  path_provider: ^2.0.12
  cloud_firestore: ^4.3.2
  google_fonts: ^3.0.1
  

dev_dependencies:
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


